import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  headercontainer: {
    width: "100%",
    height: 110,

    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  headerText: {
    fontSize: 30,
    fontWeight: "bold",
    fontFamily: "inter",
    textAlign: "center",
    paddingTop: 20,
  },
  playerTurncontainer: {
    width: "90%",
    height: 100,
    marginTop: 5,
    justifyContent: "center",
    alignItems: "center",
    elevation: 0.5,
    borderRadius: 10,
    borderWidth: 0.1,
    backgroundColor: "#fff",
    borderColor: "#ccc",
  },
  choiceText: {
    fontSize: 30,
    fontWeight: "bold",
    fontFamily: "inter",
    textAlign: "center",
    color: "#7C4DFF",
  },
  ScoreContainer: {
    width: "100%",
    height: 100,
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 30,
  },
  playercard: {
    width: "40%",
    height: 100,
    justifyContent: "center",
    alignItems: "center",

    elevation: 0.5,
    borderRadius: 10,
    borderWidth: 0.1,
    backgroundColor: "#fff",
    borderColor: "#ccc",
  },
  scorewinText: {
    color: "#1a922cb9",
  },
  scoreloseText: {
    color: "#bd2e2e",
  },

  gameContainer: {
    width: "90%",
    height: 280,
    marginTop: 10,
    justifyContent: "center",
    alignItems: "center",
    elevation: 0.5,
    borderRadius: 10,
    borderWidth: 0.1,
    backgroundColor: "#fff",
    borderColor: "#ccc",
  },
  box: {
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    elevation: 0.5,
    borderWidth: 0.5,
    backgroundColor: "#d9e9eb",
    borderColor: "#4e99cf",
  },
  NEWGAME: {
    width: "50%",
    height: 40,
    backgroundColor: "#7C4DFF",
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 10,
    opacity: 0.9,
    flexDirection: "row",
    gap: 5,
  },
  footer: {
    width: "100%",
    height: 90,
    backgroundColor: "#fff",
    justifyContent: "space-evenly",
    marginTop: 40,
    flexDirection: "row",
    alignItems: "center",
  },
  footerText: {
    fontSize: 12,
    fontWeight: "bold",
    paddingBottom: 20,
  },
  footerIcon: {
    alignItems: "center",
    justifyContent: "center",
  },
});
export default styles;
